name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Swift Package
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
        
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Build
      working-directory: ./JuicelineGeideaSDK
      run: swift build -v
      
    - name: Run tests
      working-directory: ./JuicelineGeideaSDK
      run: swift test -v --enable-code-coverage
      
    - name: Generate test coverage
      working-directory: ./JuicelineGeideaSDK
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/JuicelineGeideaSDKPackageTests.xctest/Contents/MacOS/JuicelineGeideaSDKPackageTests \
          -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./JuicelineGeideaSDK/coverage.lcov
        fail_ci_if_error: true

  lint:
    name: Swift Lint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      working-directory: ./JuicelineGeideaSDK
      run: swiftlint --strict

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  deploy:
    name: Deploy Documentation
    runs-on: macos-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
        
    - name: Generate documentation
      working-directory: ./JuicelineGeideaSDK
      run: |
        swift package --allow-writing-to-directory docs \
          generate-documentation --target JuicelineGeideaSDK \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path juiceline \
          --output-path docs
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./JuicelineGeideaSDK/docs